### ISSUE TITLE
Failed to resolve entry for package "@govuk-react/icon-crown"

### ISSUE THREAD

**Issue by juliaisnotavailable** [govuk-react/govuk-react#1579]
**Describe the bug**
When running `npm run dev` after creating a new React+Vite project the following error is observed:

```
✘ [ERROR] Failed to resolve entry for package "@govuk-react/icon-crown". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:48054:17)
    at resolvePackageEntry (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:48051:5)
    at tryNodeResolve (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:47821:20)
    at Context.resolveId (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:47582:28)
    at Object.resolveId (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50778:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:67798:21
    at async file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:48394:34
    at async requestCallbacks.on-resolve (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:1374:22)
    at async handleRequest (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:732:11)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1293:20:
      1293 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:48374:19)
    at handlePlugins (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:1293:21)
    at buildOrContextImpl (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:979:5)
    at Object.buildOrContext (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:788:5)
    at /Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:2223:68
    at new Promise (<anonymous>)
    at Object.context (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:2223:27)
    at Object.context (/Users/john/tmp/vite-project/node_modules/esbuild/lib/main.js:2048:58)
    at prepareEsbuildOptimizerRun (file:///Users/john/tmp/vite-project/node_modules/vite/dist/node/chunks/dep-G-px366b.js:52553:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/@govuk-react/top-nav/dist/govuk-react-top-nav.esm.js:6:22:
      6 │ import CrownIcon from '@govuk-react/icon-crown';
```
Node and npm versions:
```
➜  ~ npm -v
10.2.4
➜  ~ node -v
v20.11.1
```

**To Reproduce**
```
➜ mkdir tmp
➜ cd tmp
➜ npm create vite@latest                                  
✔ Project name: … vite-project
✔ Select a framework: › React
✔ Select a variant: › TypeScript

Scaffolding project in /Users/john/tmp/vite-project...

Done. Now run:

  cd vite-project
  npm install
  npm run dev

➜  cd vite-project 
➜  npm install govuk-react                                 

added 337 packages, and audited 338 packages in 17s

74 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  npm install

up to date, audited 338 packages in 989ms

74 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜ npm run dev

> vite-project@0.0.0 dev
> vite

Port 5173 is in use, trying another one...

  VITE v5.1.5  ready in 357 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

```

**Expected behavior**
The application starts with no errors

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.1 (23B81)
 - Browser: n/a
 - Version: n/a

**Comment by penx** [comment]
Duplicate of https://github.com/govuk-react/govuk-react/issues/1341
